<?xml version='1.0' encoding='UTF-8'?>
<esdl:EnergySystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:esdl="http://www.tno.nl/esdl" id="e48ed4fa-6051-4bab-ba54-27c581be21a0" description="Autogenerated based on GNF file Alliander Arch8 Net4_newconnectionphase.gnf" name="Alliander Arch8 Net4">
  <energySystemInformation xsi:type="esdl:EnergySystemInformation" id="63a26070-be56-4b8f-9230-c806d5172315"/>
  <parties xsi:type="esdl:Parties">
    <party xsi:type="esdl:Party" id="cb9659b9-c196-49bc-aab8-41904b57cab4" name="DSO"/>
  </parties>
  <measures xsi:type="esdl:Measures" name="measures" id="751ede41-201d-4dfd-93a1-638ae70777d4">
    <measure xsi:type="esdl:Measure" name="bandwidth tariff" id="aba64d59-d1fd-4d8a-a6fd-058e3338b959" description="5000">
      <costInformation xsi:type="esdl:CostInformation" id="a581a337-9ac3-44b8-b789-835e2a91e2f2" name="cost_information">
        <variableOperationalAndMaintenanceCosts xsi:type="esdl:SingleValue" id="45c42331-7088-40d6-8331-f5c2f07afd1f" name="high_bandwidth_price" value="2.0"/>
        <fixedOperationalAndMaintenanceCosts xsi:type ="esdl:SingleValue" id="0ac9598c-5e71-49fe-940d-d039c8b64be3" name="low_bandwidth_price" value="1.0"/>
      </costInformation>
    </measure>
  </measures>
  <instance xsi:type="esdl:Instance" id="539b8f85-8f6a-4486-b966-4cc15bb17b34" name="Instance name">
    <area xsi:type="esdl:Area" name="Area name" id="ea5a1a30-4b2f-4721-8d5e-fc36147a74df">
      <asset xsi:type="esdl:Joint" name="Node1" originalIdInSource="1" id="9df0c0f6-1692-4d2d-a811-44078cfaee9f">
        <port xsi:type="esdl:InPort" id="8f727e30-bb01-40b6-a6de-764084905651" name="In" connectedTo="7e7a3cb8-7f0b-4b82-9f9b-504aba6ef409"/>
        <port xsi:type="esdl:OutPort" id="67c9a496-9809-4aee-bff6-f14ba01f62eb" name="Out" connectedTo="e8f99245-2ad3-47e5-8833-b32288ff336e"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9393039052446257" lat="40.3442481544872"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node2" originalIdInSource="2" id="e39749a5-2d31-48dc-8729-2a8e5044abeb">
        <port xsi:type="esdl:InPort" id="a4cc744f-b0ea-4aab-b436-6aba3d7fa442" name="In" connectedTo="a0633019-a39a-4cc8-a529-663eeadc06b9"/>
        <port xsi:type="esdl:OutPort" id="4fc5a130-6654-402a-a36e-656187aa8fbf" name="Out"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9928505899402378" lat="40.328874053316184"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node3" originalIdInSource="3" id="cf61deee-dbdc-4edf-b78a-a17e0c73b66b">
        <port xsi:type="esdl:InPort" id="410e722a-78d7-4c95-a35a-528d34e6e3f4" name="In" connectedTo="3cebe271-ee07-42bf-9689-d2bd49150a58"/>
        <port xsi:type="esdl:OutPort" id="5736e7a9-e7e2-4115-9fdc-4ebcc0722cc4" name="Out" connectedTo="19d845b6-71dd-47cf-b13f-aa225a32e1c3 1233ad56-875f-4629-b675-a56b08f3e68d"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9479801674533954" lat="40.35353454320812"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node4" originalIdInSource="4" id="3d7e7f40-16d5-4dd8-81c2-20a3302e4578">
        <port xsi:type="esdl:InPort" id="55575e94-cdcf-4e6c-90e3-8c8cfb671b37" name="In" connectedTo="3187918a-f3f0-4be0-bd35-abf1e93a0e2b"/>
        <port xsi:type="esdl:OutPort" id="a72f39a2-5da4-4e56-bdce-eebb17638f41" name="Out" connectedTo="00bb059f-45ac-479a-b7bc-5bbe9f26ed8b"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9166954108830483" lat="40.37038142820745"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node5" originalIdInSource="5" id="1baeecdd-0cfa-4a69-bc4c-afe0cbee91bf">
        <port xsi:type="esdl:InPort" id="749305f7-aa26-49f0-9b89-04e5de0ac8ae" name="In" connectedTo="7cbf009e-b64d-4787-af27-7f021d0369e3"/>
        <port xsi:type="esdl:OutPort" id="125a2ab3-e4b8-4a93-bdba-d5c77cebf721" name="Out" connectedTo="2dda0637-1dd0-4365-9b02-1975c7f6ab42"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9351401254765817" lat="40.360296039630434"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node6" originalIdInSource="6" id="442bf58d-214e-4421-a823-7a8bedf0d6cc">
        <port xsi:type="esdl:InPort" id="b1bfa4b2-aebe-4908-b366-7e27eef02606" name="In" connectedTo="cb4c6484-8845-4d1f-9949-09f6dad6ef09"/>
        <port xsi:type="esdl:OutPort" id="02f1d66e-4240-46e0-8385-acc3231e1a90" name="Out" connectedTo="058e9137-8f20-4045-8375-73c90442624b e25f6027-58a0-4069-86b6-89bbd3161c5f"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9926057351480715" lat="40.3290419999893"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node7" originalIdInSource="7" id="86d10bf9-6ab2-4379-b3ec-4490f4365928">
        <port xsi:type="esdl:InPort" id="4bdb9da6-429a-49f4-bb6c-8f9b569f8495" name="In" connectedTo="e1589d6c-1385-4976-ad21-a5744ad7e4ca"/>
        <port xsi:type="esdl:OutPort" id="4ec0e4aa-bda9-466c-b74e-cfd4fcdcf241" name="Out" connectedTo="bb130fe0-b81e-4ae3-9dcd-ff07d242fb4c 27c3a6f1-b7d7-4df4-b79e-a6bbef1dcf44"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9413913640242653" lat="40.34772531879825"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node8" originalIdInSource="8" id="840a02bf-dea9-4c4b-aa9a-f577d9ba619e">
        <port xsi:type="esdl:InPort" id="a27f7bf8-0583-4388-a41b-3ad20c699b0a" name="In" connectedTo="0117e67c-4d5f-476d-ad20-4ac321aba822"/>
        <port xsi:type="esdl:OutPort" id="fadae9a3-e4f7-4ce6-8485-b2038d5348a5" name="Out"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9004272415545254" lat="40.37930953109506"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node9" originalIdInSource="9" id="3e1eec10-03e0-4bfe-9805-48b3588e3676">
        <port xsi:type="esdl:InPort" id="fc6525ce-667b-405d-9919-a3bf2e8403f2" name="In" connectedTo="90c21d40-b797-4c6d-be3e-7259a603985c"/>
        <port xsi:type="esdl:OutPort" id="bb63046b-c050-4778-909a-70896b10f116" name="Out" connectedTo="e773ce32-2cd1-4d89-a482-543faf07cebf e45b2146-3e0a-4bd5-988e-fa56e7a0ecbf"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9395239116585641" lat="40.34443587759388"/>
      </asset>
      <asset xsi:type="esdl:Joint" name="Node13" originalIdInSource="13" id="68a8e13f-2b2a-46c3-ac85-4896878ab881">
        <port xsi:type="esdl:InPort" id="0e763d8e-2194-4dcc-ba74-e4da4561307d" name="In" connectedTo="fd364cdc-59f0-47f5-8463-905aa70d6184"/>
        <port xsi:type="esdl:OutPort" id="76077960-eb51-4afd-9d72-994d7c950f3b" name="Out" connectedTo="27231db4-249d-421b-a9d9-ed96e3b99332"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="3.3087872444269997" lat="47.992648274305736"/>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable1" originalIdInSource="1" length="1.0" id="4baca81d-f563-4af5-bad9-85f90ea12894" assetType="4x150Al_4x6Cu_50CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="e8f99245-2ad3-47e5-8833-b32288ff336e" name="In" connectedTo="67c9a496-9809-4aee-bff6-f14ba01f62eb"/>
        <port xsi:type="esdl:OutPort" id="90c21d40-b797-4c6d-be3e-7259a603985c" name="Out" connectedTo="fc6525ce-667b-405d-9919-a3bf2e8403f2"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9393039052446257" lat="40.3442481544872"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9395239116585641" lat="40.34443587759388"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable2" originalIdInSource="2" length="24.5" id="10ef23ed-1d9a-48ce-981e-9b98f220620a" assetType="4x150Al_4x6Cu_50CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="e45b2146-3e0a-4bd5-988e-fa56e7a0ecbf" name="In" connectedTo="bb63046b-c050-4778-909a-70896b10f116"/>
        <port xsi:type="esdl:OutPort" id="e1589d6c-1385-4976-ad21-a5744ad7e4ca" name="Out" connectedTo="4bdb9da6-429a-49f4-bb6c-8f9b569f8495"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9395239116585641" lat="40.34443587759388"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9413913640242653" lat="40.34772531879825"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable3" originalIdInSource="3" length="44.9" id="5d5782f8-8c49-49ae-8a8d-4b7959c1f450" assetType="4x150Al_4x6Cu_50CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="27c3a6f1-b7d7-4df4-b79e-a6bbef1dcf44" name="In" connectedTo="4ec0e4aa-bda9-466c-b74e-cfd4fcdcf241"/>
        <port xsi:type="esdl:OutPort" id="3cebe271-ee07-42bf-9689-d2bd49150a58" name="Out" connectedTo="410e722a-78d7-4c95-a35a-528d34e6e3f4"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9413913640242653" lat="40.34772531879825"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9479801674533954" lat="40.35353454320812"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable4" originalIdInSource="4" length="236.5" id="d210ec53-3ca7-4d77-b069-2b091a4a740e" assetType="4x95Al_4x6Cu_35CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="19d845b6-71dd-47cf-b13f-aa225a32e1c3" name="In" connectedTo="5736e7a9-e7e2-4115-9fdc-4ebcc0722cc4"/>
        <port xsi:type="esdl:OutPort" id="cb4c6484-8845-4d1f-9949-09f6dad6ef09" name="Out" connectedTo="b1bfa4b2-aebe-4908-b366-7e27eef02606"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9479801674533954" lat="40.35353454320812"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9926057351480715" lat="40.3290419999893"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable5" originalIdInSource="5" length="1.6" id="490ea2a5-e7fa-420c-91a8-3468550e38d1" assetType="4x95Al_4x6Cu_35CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="e25f6027-58a0-4069-86b6-89bbd3161c5f" name="In" connectedTo="02f1d66e-4240-46e0-8385-acc3231e1a90"/>
        <port xsi:type="esdl:OutPort" id="a0633019-a39a-4cc8-a529-663eeadc06b9" name="Out" connectedTo="a4cc744f-b0ea-4aab-b436-6aba3d7fa442"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9926057351480715" lat="40.3290419999893"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9928505899402378" lat="40.328874053316184"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable6" originalIdInSource="6" length="66.3" id="fdcdfdf6-69c0-428b-aea8-aca35a9840b1" assetType="4x95Al_4x6Cu_35CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="1233ad56-875f-4629-b675-a56b08f3e68d" name="In" connectedTo="5736e7a9-e7e2-4115-9fdc-4ebcc0722cc4"/>
        <port xsi:type="esdl:OutPort" id="7cbf009e-b64d-4787-af27-7f021d0369e3" name="Out" connectedTo="749305f7-aa26-49f0-9b89-04e5de0ac8ae"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9479801674533954" lat="40.35353454320812"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9351401254765817" lat="40.360296039630434"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable8" originalIdInSource="8" length="85.8" id="218d0420-d120-4687-8f2f-7ffd77f3a292" assetType="4x95Al_4x6Cu_35CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="00bb059f-45ac-479a-b7bc-5bbe9f26ed8b" name="In" connectedTo="a72f39a2-5da4-4e56-bdce-eebb17638f41"/>
        <port xsi:type="esdl:OutPort" id="0117e67c-4d5f-476d-ad20-4ac321aba822" name="Out" connectedTo="a27f7bf8-0583-4388-a41b-3ad20c699b0a"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9166954108830483" lat="40.37038142820745"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9004272415545254" lat="40.37930953109506"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="Cable9" originalIdInSource="9" length="97.8" id="56b34327-32e0-403e-85ac-88a837cdfdef" assetType="4x95Al_4x6Cu_35CuAs_V_VMvKhsas">
        <port xsi:type="esdl:InPort" id="2dda0637-1dd0-4365-9b02-1975c7f6ab42" name="In" connectedTo="125a2ab3-e4b8-4a93-bdba-d5c77cebf721"/>
        <port xsi:type="esdl:OutPort" id="3187918a-f3f0-4be0-bd35-abf1e93a0e2b" name="Out" connectedTo="55575e94-cdcf-4e6c-90e3-8c8cfb671b37"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9351401254765817" lat="40.360296039630434"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9166954108830483" lat="40.37038142820745"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Transformer" voltageSecundary="0.38" name="Transformer1" voltagePrimary="10.0" originalIdInSource="1" id="d2411d31-08fd-4965-bc85-78a1fb4b3b8d" assetType="10000_380_V_150_kVA_Smit">
        <port xsi:type="esdl:InPort" id="27231db4-249d-421b-a9d9-ed96e3b99332" name="In" connectedTo="76077960-eb51-4afd-9d72-994d7c950f3b"/>
        <port xsi:type="esdl:OutPort" id="7e7a3cb8-7f0b-4b82-9f9b-504aba6ef409" name="Out" connectedTo="8f727e30-bb01-40b6-a6de-764084905651"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="3.3087872444269997" lat="47.992648274305736"/>
      </asset>
      <asset xsi:type="esdl:Import" name="Source1" originalIdInSource="1" id="35c99886-75dc-482e-9747-7a84d9d739ad" assetType="10.5">
        <port xsi:type="esdl:OutPort" id="fd364cdc-59f0-47f5-8463-905aa70d6184" name="Out" connectedTo="0e763d8e-2194-4dcc-ba74-e4da4561307d"/>
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="3.3087872444269997" lat="47.992648274305736"/>
      </asset>
      <asset xsi:type="esdl:Building" name="Home61" originalIdInSource="6_1" id="6db5e8b9-2ea3-4f04-9ef9-08283bd41b02">
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9972905224013564" lat="40.33209278910092"/>
        <asset xsi:type="esdl:EConnection" name="ConnectionHome61" originalIdInSource="6_1" id="1a0c45a7-eb0c-4871-83fa-945148c30d6c">
          <port xsi:type="esdl:InPort" id="14240bd0-07eb-44a2-97ca-0088d8b4fa92" name="In" connectedTo="7134c518-3333-4dd5-9e75-318789a36f6f"/>
          <port xsi:type="esdl:OutPort" id="f2ff79d3-e999-41da-8318-fb8de89ab5b6" name="OutPh1" connectedTo="fecf4d53-093e-44b7-a462-a431e0d1f422"/>
          <port xsi:type="esdl:OutPort" id="d4047e77-ba08-4adb-ac7f-171482a057f6" name="OutPh2" connectedTo="de9953f4-2499-45ad-a94b-2c1568045ab1"/>
          <port xsi:type="esdl:OutPort" id="95436d57-972e-4f65-af09-cacff7b1dfe9" name="OutPh3" connectedTo="f8925014-1646-4c11-b4ed-f46628cb1f4b"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="52.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome61Ph1" originalIdInSource="6_1" id="1366c793-38a9-4237-8851-dc066aff6507">
          <port xsi:type="esdl:InPort" id="fecf4d53-093e-44b7-a462-a431e0d1f422" name="In" connectedTo="f2ff79d3-e999-41da-8318-fb8de89ab5b6"/>
          <port xsi:type="esdl:OutPort" id="4baaa380-5a7b-47c1-acf4-ea9ed9b4993a" name="Out" connectedTo="368a6601-1ede-47bb-ad00-dc6c7686acb3"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="360.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome61Ph2" originalIdInSource="6_1" id="9d6fe7f8-dd63-4db5-99b9-4453971ac04c">
          <port xsi:type="esdl:InPort" id="de9953f4-2499-45ad-a94b-2c1568045ab1" name="In" connectedTo="d4047e77-ba08-4adb-ac7f-171482a057f6"/>
          <port xsi:type="esdl:OutPort" id="7b8326bb-b6f3-4b9c-800c-0237a16ca56e" name="Out" connectedTo="db0fd300-e88c-4416-bdac-5282dc1b3bfd"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome61Ph3" originalIdInSource="6_1" id="2d4ec1fd-9f83-4304-8446-29d4c3027aa3">
          <port xsi:type="esdl:InPort" id="f8925014-1646-4c11-b4ed-f46628cb1f4b" name="In" connectedTo="95436d57-972e-4f65-af09-cacff7b1dfe9"/>
          <port xsi:type="esdl:OutPort" id="c9e7dc35-5e5a-4dfe-a1e8-fc4e86863a7a" name="Out" connectedTo="ce0d4b33-0fab-4e40-b9cb-ee73f1685e36"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="160.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="DemandHome61" originalIdInSource="6_1" id="a3b51e59-c961-4210-9637-d67e1e9e6aed" powerFactor="0.95">
          <port xsi:type="esdl:InPort" id="368a6601-1ede-47bb-ad00-dc6c7686acb3" name="In_Ph1" connectedTo="4baaa380-5a7b-47c1-acf4-ea9ed9b4993a"/>
          <port xsi:type="esdl:InPort" id="db0fd300-e88c-4416-bdac-5282dc1b3bfd" name="In_Ph2" connectedTo="7b8326bb-b6f3-4b9c-800c-0237a16ca56e"/>
          <port xsi:type="esdl:InPort" id="ce0d4b33-0fab-4e40-b9cb-ee73f1685e36" name="In_Ph3" connectedTo="c9e7dc35-5e5a-4dfe-a1e8-fc4e86863a7a"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="445.0" lat="260.0"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="CableHome61" originalIdInSource="6_1" length="34.6" id="8e58b6d0-a4b4-4bc4-99d3-578cf70d39e9" assetType="4x6Cu_4x1Cu__GPLKh">
        <port xsi:type="esdl:InPort" id="058e9137-8f20-4045-8375-73c90442624b" name="In" connectedTo="02f1d66e-4240-46e0-8385-acc3231e1a90"/>
        <port xsi:type="esdl:OutPort" id="7134c518-3333-4dd5-9e75-318789a36f6f" name="Out" connectedTo="14240bd0-07eb-44a2-97ca-0088d8b4fa92"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9926057351480715" lat="40.3290419999893"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9972905224013564" lat="40.33209278910092"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="Home_7_1" originalIdInSource="7_1" id="c5be5a49-c871-4325-85f2-640b6448cded">
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9389406826711797" lat="40.34940353393508"/>
        <asset xsi:type="esdl:EConnection" name="ConnectionHome71" originalIdInSource="7_1" id="a36cc94b-9802-42e0-89e7-e8017542f6cf">
          <port xsi:type="esdl:InPort" id="b5ff6f01-1271-493b-8be6-58c1aee30cb5" name="In" connectedTo="64209653-cfe0-449d-ad11-7872c8db3a29"/>
          <port xsi:type="esdl:OutPort" id="72bb5db9-da56-43a3-9984-9a7ffda476ad" name="OutPh1" connectedTo="4e56fbcb-933c-4589-82ea-77c93e2a76f6"/>
          <port xsi:type="esdl:OutPort" id="a6b03674-4ea1-41fe-9d56-0089ef3a4693" name="OutPh2" connectedTo="3c1fd00a-bbf6-41b1-bb74-8f3049bf18d5"/>
          <port xsi:type="esdl:OutPort" id="7615335b-ea7a-4fb8-a825-853776868460" name="OutPh3" connectedTo="a208bc9c-1360-434a-be29-064b75c83510"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="52.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome71Ph1" originalIdInSource="7_1" id="217e2cf8-b02f-4943-8326-585e78a44109">
          <port xsi:type="esdl:InPort" id="4e56fbcb-933c-4589-82ea-77c93e2a76f6" name="In" connectedTo="72bb5db9-da56-43a3-9984-9a7ffda476ad"/>
          <port xsi:type="esdl:OutPort" id="16be9e29-6b37-4c29-9f8c-ab13228ff844" name="Out" connectedTo="024c8dac-533d-452d-98aa-139205811367"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="360.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome71Ph2" originalIdInSource="7_1" id="6610ca60-4e10-44e6-b5be-4679c7412fbb">
          <port xsi:type="esdl:InPort" id="3c1fd00a-bbf6-41b1-bb74-8f3049bf18d5" name="In" connectedTo="a6b03674-4ea1-41fe-9d56-0089ef3a4693"/>
          <port xsi:type="esdl:OutPort" id="cd4d66c0-0db9-43a1-92d7-5ccde0646b4e" name="Out" connectedTo="5f22e260-b2ae-4d9f-b60f-5bb7f68c7f95"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="Connection_Home71Ph3" originalIdInSource="7_1" id="9e97b6c0-2907-4471-a1c3-59eb9715162c">
          <port xsi:type="esdl:InPort" id="a208bc9c-1360-434a-be29-064b75c83510" name="In" connectedTo="7615335b-ea7a-4fb8-a825-853776868460"/>
          <port xsi:type="esdl:OutPort" id="a507ef88-f5f9-4714-a70d-affd851d50ba" name="Out" connectedTo="78f41a25-e0b2-4631-9d4a-8680a4e26937"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="160.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="DemandHome71" originalIdInSource="7_1" id="f0d61481-d2e5-4cf3-8fab-e7f387299c7b" powerFactor="0.95">
          <port xsi:type="esdl:InPort" id="024c8dac-533d-452d-98aa-139205811367" name="In_Ph1" connectedTo="16be9e29-6b37-4c29-9f8c-ab13228ff844"/>
          <port xsi:type="esdl:InPort" id="5f22e260-b2ae-4d9f-b60f-5bb7f68c7f95" name="In_Ph2" connectedTo="cd4d66c0-0db9-43a1-92d7-5ccde0646b4e"/>
          <port xsi:type="esdl:InPort" id="78f41a25-e0b2-4631-9d4a-8680a4e26937" name="In_Ph3" connectedTo="a507ef88-f5f9-4714-a70d-affd851d50ba"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="445.0" lat="260.0"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="CableHome71" originalIdInSource="7_1" length="13.9" id="26c5630a-7a19-4485-8253-1c272bbf7aba" assetType="4x6Cu_4x1Cu__GPLKh">
        <port xsi:type="esdl:InPort" id="bb130fe0-b81e-4ae3-9dcd-ff07d242fb4c" name="In" connectedTo="4ec0e4aa-bda9-466c-b74e-cfd4fcdcf241"/>
        <port xsi:type="esdl:OutPort" id="64209653-cfe0-449d-ad11-7872c8db3a29" name="Out" connectedTo="b5ff6f01-1271-493b-8be6-58c1aee30cb5"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9413913640242653" lat="40.34772531879825"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9389406826711797" lat="40.34940353393508"/>
        </geometry>
      </asset>
      <asset xsi:type="esdl:Building" name="Home91" originalIdInSource="9_1" id="30b2982f-8372-4c86-9c0c-626c7baa007e">
        <geometry xsi:type="esdl:Point" CRS="WGS84" lon="0.9397689630665909" lat="40.34426805809611"/>
        <asset xsi:type="esdl:EConnection" name="ConnectionHome91" originalIdInSource="9_1" id="bb93de79-0d9e-4cf2-8794-ebac2d238f45">
          <port xsi:type="esdl:InPort" id="4d5e5621-7d7b-4e90-945f-8de723eece63" name="In" connectedTo="20608c50-3d16-4cae-af3d-505d6ca16060"/>
          <port xsi:type="esdl:OutPort" id="a8a443a2-3026-4f0e-9735-4b67f3f3e700" name="OutPh1" connectedTo="24efeb13-9a02-4d68-a061-160f22b7d4c5"/>
          <port xsi:type="esdl:OutPort" id="5abf535c-160c-412b-97c1-3ba51ae643ad" name="OutPh2" connectedTo="d10598a2-59bb-4de4-b180-fef0817ae5cf"/>
          <port xsi:type="esdl:OutPort" id="10d0680e-e265-493e-b866-a1007fa4c4ae" name="OutPh3" connectedTo="7c33ddb5-7b89-4695-a180-e9c929de52f6"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="52.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome91Ph1" originalIdInSource="9_1" id="af383c64-a081-4e15-9794-3e3bad4b76d0">
          <port xsi:type="esdl:InPort" id="24efeb13-9a02-4d68-a061-160f22b7d4c5" name="In" connectedTo="a8a443a2-3026-4f0e-9735-4b67f3f3e700"/>
          <port xsi:type="esdl:OutPort" id="bc97ea80-8828-47d4-abf4-fe7687bcdc5d" name="Out" connectedTo="5db69f8c-1b70-4b36-b316-cda5ad92e0c3"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="360.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome91Ph2" originalIdInSource="9_1" id="41ba504e-7a80-49bc-b69e-9f1b1d6a9029">
          <port xsi:type="esdl:InPort" id="d10598a2-59bb-4de4-b180-fef0817ae5cf" name="In" connectedTo="5abf535c-160c-412b-97c1-3ba51ae643ad"/>
          <port xsi:type="esdl:OutPort" id="849116d9-a73f-4d08-9f7a-3fde19762b54" name="Out" connectedTo="6683dc2a-6eed-4a33-a7ac-e13a8126b34c"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="260.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityNetwork" name="ConnectionHome91Ph3" originalIdInSource="9_1" id="da4c360c-6b82-4c48-b696-091e652dcb07">
          <port xsi:type="esdl:InPort" id="7c33ddb5-7b89-4695-a180-e9c929de52f6" name="In" connectedTo="10d0680e-e265-493e-b866-a1007fa4c4ae"/>
          <port xsi:type="esdl:OutPort" id="0669d324-84b1-4cb5-bade-183786cbb009" name="Out" connectedTo="480116e1-721d-41bc-b40a-c2002a455e42"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="236.0" lat="160.0"/>
        </asset>
        <asset xsi:type="esdl:ElectricityDemand" name="DemandHome91" originalIdInSource="9_1" id="b64adaf7-f407-45ae-9b13-9c8945d5bd31" powerFactor="0.95">
          <port xsi:type="esdl:InPort" id="5db69f8c-1b70-4b36-b316-cda5ad92e0c3" name="In_Ph1" connectedTo="bc97ea80-8828-47d4-abf4-fe7687bcdc5d"/>
          <port xsi:type="esdl:InPort" id="6683dc2a-6eed-4a33-a7ac-e13a8126b34c" name="In_Ph2" connectedTo="849116d9-a73f-4d08-9f7a-3fde19762b54"/>
          <port xsi:type="esdl:InPort" id="480116e1-721d-41bc-b40a-c2002a455e42" name="In_Ph3" connectedTo="0669d324-84b1-4cb5-bade-183786cbb009"/>
          <geometry xsi:type="esdl:Point" CRS="Simple" lon="445.0" lat="260.0"/>
        </asset>
      </asset>
      <asset xsi:type="esdl:ElectricityCable" name="CableHome91" originalIdInSource="9_1" length="1.0" id="bfc9b677-126e-4902-a037-401d620c682a" assetType="4x16Cu__VG_YMvKas_mb_0p6_1kV_as16">
        <port xsi:type="esdl:InPort" id="e773ce32-2cd1-4d89-a482-543faf07cebf" name="In" connectedTo="bb63046b-c050-4778-909a-70896b10f116"/>
        <port xsi:type="esdl:OutPort" id="20608c50-3d16-4cae-af3d-505d6ca16060" name="Out" connectedTo="4d5e5621-7d7b-4e90-945f-8de723eece63"/>
        <geometry xsi:type="esdl:Line">
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9395239116585641" lat="40.34443587759388"/>
          <point xsi:type="esdl:Point" CRS="WGS84" lon="0.9397689630665909" lat="40.34426805809611"/>
        </geometry>
      </asset>
    </area>
  </instance>
</esdl:EnergySystem>
